### ISSUE TITLE
Run the tests with different install modes

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#261] opened 2021-11-17 13:53 UTC
The e2e tests are only run with own namespace mode. Look into running the same tests with single namespace and all namespace modes.

**Comment by halim-lee** [comment] 2023-04-14 14:09
Duplicate of https://github.com/WASdev/websphere-liberty-operator/issues/365. Closing

**Closed by halim-lee** 2023-04-14 14:09 UTC
Labels: help wanted, testing, low
